#!/usr/bin/env bash

function check_command {
  local command=$1
  command ${command} >/dev/null 2>&1
  if [ "$?" != "0" ]; then
    echo "⨯ ${command} not found"
    echo "Please install ${command}!"
    exit 1
  fi
  echo "✓ ${command} found"
}

function check_requirements {
  check_command "docker"
  check_command "mutagen"
}

function startup {
  echo "Starting stack. This might take a while on the first run."
  mutagen project start || mutagen project resume
}

function attach_to_web {
  echo "Attaching to the application container. Use Ctrl+p Ctrl+q to leave."
  docker attach backoffice_web_1
}

function tail_logs {
  docker-compose logs --follow
}

function shutdown {
  echo "Shutting down..."
  mutagen project pause
  echo "done"
}

function run_start {
  check_requirements
  startup
  attach_to_web
}

function run_stop {
  shutdown
}

function run_rebuild {
  mutagen project terminate
  run_start
}

function run_clean {
  mutagen project terminate
  rm -fr _build deps assets/node_modules
  docker-compose down --rmi=all --volumes
}

function run_update {
  git fetch --prune
  git merge --ff origin/master
}

function run_iex {
  local command="iex -S mix $@"
  run_command web ${command}
}

function run_mix {
  local command="mix $@"
  run_command web ${command}
}

function run_update_translations {
  run_command web "mix do gettext.extract, gettext.merge priv/gettext --locale de"
  echo "Extracted and updated translation strings. Please translate."
}

function run_tests {
  local command="mix test $@"
  run_command web ${command}
}

function run_tests_in_watch_mode {
  local command="mix test.watch $@"
  run_command web ${command}
}

function run_yarn {
  local command="cd assets && yarn $@"
  run_command web ${command}
}

function run_build_production {
  local command="cd assets && yarn deploy && cd .. && mix phx.digest"
  run_command web ${command}
}

function run_command {
  local container_name=${1}
  local command="${@:2}"
  docker-compose exec ${container_name} bash -c "${command}"
}

function print_usage {
  echo "Usage: ./dev [command] [args]"
}

function show_help {
  cat  << EOF
The following commands are supported:

./dev start                 # Start the development stack
./dev stop                  # Stop the development stack
./dev rebuild               # Rebuild the images and restart the development stack
./dev reset                 # Reset the stack (including volumes and images)
./dev update                # Update from master branch
./dev iex                   # Spawn IEx session
./dev mix                   # Run mix commands
./dev translations.update   # Run the (Elixir) tests
./dev test                  # Run the (Elixir) tests
./dev test.watch            # Run the (Elixir) tests in watch mode
./dev yarn                  # Run a Yarn command
./dev build.prod            # Run production build for assets
./dev execute               # Run arbitrary command in a container

To get information about a single command use ./dev [command] --help
EOF
}

function maybe_show_command_help {
  if [ "${1}" == "--help" ]; then
    return
  fi
  if [ "${2}" != "--help" ]; then
    return
  fi
  case ${command} in
    "start"|"s")
      print_help_for_start
      ;;
    "stop"|"st")
      print_help_for_stop
      ;;
    "rebuild"|"rb")
      print_help_for_rebuild
      ;;
    "reset"|"rs")
      print_help_for_reset
      ;;
    "update"|"u")
      print_help_for_update
      ;;
    "iex"|"i")
      print_help_for_iex
      ;;
    "mix"|"m")
      print_help_for_mix
      ;;
    "translations.update"|"tu")
      print_help_for_update_translations
      ;;
    "test"|"t")
      print_help_for_test
      ;;
    "test.watch"|"tw")
      print_help_for_test_watch
      ;;
    "yarn"|"y")
      print_help_for_yarn
      ;;
    "build.prod"|"bp")
      print_help_for_build_production
      ;;
    "execute"|"e")
      print_help_for_execute
      ;;
    *) echo "No help found for '${command}'"
  esac
  exit 0
}

function print_help_for_start {
  cat << EOF
# start

shortcut: s

The 'start' command checks if the required tools (Docker, Mutagen) are available.
If so it will check and create or load the images needed for the application.
It starts the application stack with all containers and opens the logs.
Stop the command with ctrl-c. This will stop the stack.
EOF
}

function print_help_for_stop {
  cat << EOF
# stop

shortcut: st

The 'stop' command will stop the stack. All data and containers will be preserved.
EOF
}

function print_help_for_rebuild {
  cat << EOF
# rebuild

shortcut: rb

The 'rebuild' command will tear down and rebuild the containers.
The volumes and images will be preserved.
EOF
}

function print_help_for_reset {
  cat << EOF
# reset

shortcut: rs

The 'reset' command tears down the application and removes all built images and
volumes.
This is useful to start over.
EOF
}

function print_help_for_update {
  cat << EOF
# update

shortcut: u

The 'update' command fetches the latest upstream state and fast-forward merges
the master branch.
EOF
}

function print_help_for_iex {
  cat << EOF
# iex

shortcut: i

The 'iex' command spawns a new IEx session for the project.
EOF
}

function print_help_for_mix {
  cat << EOF
# mix

shortcut: m

The 'mix' command can be used to run mix commands, e.g.
./dev mix run priv/repo.seeds.exs
EOF
}

function print_help_for_update_translations {
  cat << EOF
# translations.update

shortcut: tu

The 'update_translations' command extracts and updates the application translations.
EOF
}

function print_help_for_test {
  cat << EOF
# test [test_file_path]

shortcut: t

The 'test' command runs the test suite.
To run single tests the path can be passed as an argument.
EOF
}

function print_help_for_test_watch {
  cat << EOF
# test.watch [test_file_path]

shortcut: tw

The 'test' command runs the test suite in watch mode.
To run single tests the path can be passed as an argument.
EOF
}

function print_help_for_yarn {
  cat << EOF
# yarn [args]

shortcut: y

The 'yarn' command runs Yarn commands within the web container.
EOF
}

function print_help_for_build_production {
  cat << EOF
# build.prod

shortcut: bp

The 'build.prod' command runs building the assets in prod mode. This is useful
for debugging things like CSS purging.
EOF
}

function print_help_for_execute {
  cat << EOF
# execute [container_name] [args]

shortcut: e

The 'execute' command runs arbitrary commands in the given container.
F.e. you can run './dev execute web "cd assets && yarn add my_dep -D"' to add a javascript library.
EOF
}

function main {
  local command=${1}
  local args="${@:2}"
  maybe_show_command_help ${command} ${args}
  case ${command} in
    "--help")
      show_help
      ;;
    "start"|"s")
      run_start
      ;;
    "stop"|"st")
      run_stop
      ;;
    "rebuild"|"rb")
      run_rebuild
      ;;
    "reset"|"rs")
      run_clean
      run_start
      ;;
    "update"|"u")
      run_update
      ;;
    "iex"|"i")
      run_iex ${args}
      ;;
    "mix"|"m")
      run_mix ${args}
      ;;
    "translations.update"|"tu")
      run_update_translations
      ;;
    "test"|"t")
      run_tests ${args}
      ;;
    "test.watch"|"tw")
      run_tests_in_watch_mode ${args}
      ;;
    "yarn"|"y")
      run_yarn ${args}
      ;;
    "build.prod"|"bp")
      run_build_production
      ;;
    "execute"|"e")
      run_command ${args}
      ;;
    *) print_usage; echo; show_help
  esac
}

main $@
