version: '3.7'
services:
  mutagen:
    build: ./docker/mutagen
    init: true
    container_name: backoffice-mutagen
    volumes:
      - app:/app
      - build:/app/_build
  web:
    build: ./docker/web
    stdin_open: true
    tty: true
    volumes:
      - app:/app
      - build:/app/_build
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/dealog_backoffice_dev
      - DATABASE_TEST_URL=postgres://postgres@db:5432/dealog_backoffice_test
    depends_on:
      - db
    ports:
      - 4000:4000
    command: '/run.sh'
    networks:
      - default
      - dealog_dev
  db:
    image: postgres:12.1-alpine
    command: 'postgres -c "max_connections=200"'
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
volumes:
  postgres-data:
  build:
  app:
networks:
  dealog_dev:
    external: true
