name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: sh

jobs:
  version:
    runs-on: ubuntu-latest
    name: Create version number

    steps:
      - uses: actions/checkout@v2

      - name: Set version number
        id: version
        uses: DEalog/version-action@v0.1.0
        with:
          fallback-prefix: "1.0.0-SNAPSHOT-"

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: |
            ./version.txt
          if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    name: Build Elixir project

    container: hexpm/elixir:1.11.4-erlang-23.2.7.2-alpine-3.13.3

    env:
      MIX_ENV: prod

    steps:
      - uses: actions/checkout@v2

      - name: Prepare build environment
        run: |
          apk add --no-cache build-base npm git
          npm install -g yarn

      - name: Cache Elixir dependencies
        id: mix_cache
        uses: actions/cache@v3.0.8
        with:
          path: |
            ~/.mix
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install and compile Elixir dependencies
        if: steps.mix_cache.outputs.cache-hit != 'true'
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix do deps.get, deps.compile

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node.js dependencies
        id: yarn-cache
        uses: actions/cache@v3.0.8
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node.js dependencies (from cache)
        run: (cd ./assets && yarn install)

      - name: Run webpack
        run: (cd ./assets && yarn deploy)

      - name: Dump tailwindcss config
        run: (cd ./assets && yarn dump)

      - name: Digest and compress static files
        run: mix phx.digest

      - name: Compile and release application
        run: mix do compile, release

      - name: Tar application files to keep file permissions
        run: tar -cvf app.tar ./_build/prod/rel/backoffice ./rel/run.sh

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: backoffice
          path: |
            ./app.tar
            ./CHANGELOG.md
            ./README.md
            ./.github/Dockerfile
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    name: Test Elixir project

    container: hexpm/elixir:1.11.4-erlang-23.2.7.2-alpine-3.13.3

    env:
      MIX_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db

    services:
      db:
        image: postgres:12.1-alpine
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Prepare build environment
        run: |
          apk add --no-cache build-base git

      - name: Cache Elixir dependencies
        id: mix_cache
        uses: actions/cache@v3.0.8
        with:
          path: |
            ~/.mix
            deps
          key: ${{ runner.os }}-mix-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-test

      - name: Install and compile Elixir dependencies
        if: steps.mix_cache.outputs.cache-hit != 'true'
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix do deps.get, deps.compile

      - name: Setup event store
        run: mix do event_store.create, event_store.init

      - name: Run tests
        run: mix test

  publish:
    runs-on: ubuntu-latest
    name: Dockerize and publish
    needs: [version, build, test]
    env:
      AWS_REGION: eu-central-1
      IMAGE_REPO: backoffice

    steps:
      - name: Fetch version artifact
        uses: actions/download-artifact@v2
        with:
          name: version

      - name: Fetch build artifact
        uses: actions/download-artifact@v2
        with:
          name: backoffice

      - name: Untar application files
        run: tar -xvf app.tar .

      - name: Set version
        run: |
          echo "VERSION=$(cat ./version.txt)" >> ${GITHUB_ENV}

      - name: Build image name
        run: |
          echo "IMAGE_TAG=${{ env.VERSION }}" >> ${GITHUB_ENV}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          image_name: ${{ env.IMAGE_REPO }}
          image_tag: ${{ env.IMAGE_TAG }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          dockerfile: ./.github/Dockerfile
          push_image_and_stages: false
        if: ${{ github.ref != 'refs/heads/main' }}

      - name: Build and push Docker image
        id: docker-build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          image_name: ${{ env.IMAGE_REPO }}
          image_tag: ${{ env.IMAGE_TAG }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          dockerfile: ./.github/Dockerfile
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Store docker image name
        run: echo ${{ steps.docker-build.outputs.FULL_IMAGE_NAME }} >> ./full_image_name.txt
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: dockerized-backoffice
          path: |
            ./full_image_name.txt
          if-no-files-found: error
        if: ${{ github.ref == 'refs/heads/main' }}
