name: Dev deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Dev deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Dokku deploy
        uses: vitalyliber/dokku-github-action@v6.2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PROJECT: dealog-backoffice
          HOST: dealog-backoffice.dev.munichmade.com
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Deployment Bot
          SLACK_ICON: https://github.com/DEalog/backoffice/raw/master/assets/static/images/dealog_iconlogo.png
          SLACK_TITLE: Deployment to Dev finished 🚀
          SLACK_MESSAGE: Please see https://dealog-backoffice.dev.munichmade.com for the latest version. Deployed `${{ github.sha }}`.
          SLACK_FOOTER: DEalog Backoffice dev deployment
          MSG_MINIMAL: true